name: Build & Test Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build --no-cache -t flask-devops-app .

      - name: Run container and smoke-test
        run: |
          docker run -d --name test-app -p 5000:5000 flask-devops-app
          sleep 5
          curl --fail http://localhost:5000 || (echo "App did not respond" && exit 1)
          docker rm -f test-app
